name: flutter_dubov_system_native
description: Native platform implementation of flutter_dubov_system. Uses Dart FFI to wrap the FIDE-approved CPPDubovSystem C++ engine for desktop and mobile platforms.
version: 0.0.1
homepage: https://github.com/khalil212002/flutter_dubov_system
repository: https://github.com/khalil212002/flutter_dubov_system/tree/master/flutter_dubov_system_web

environment:
  sdk: ^3.11.0

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4
  flutter_dubov_system_platform_interface: ^0.0.1
  ffi: ^2.2.0
  native_assets_cli: ^0.18.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0

flutter:
  plugin:
    implements: flutter_dubov_system
    platforms:
      windows:
        dartPluginClass: DubovSystemNative
      macos:
        dartPluginClass: DubovSystemNative
      linux:
        dartPluginClass: DubovSystemNative
      android:
        dartPluginClass: DubovSystemNative
      ios:
        dartPluginClass: DubovSystemNative
